# -*- coding: utf-8 -*-
"""Untitled4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15UXifiEfrg_ZGhFoZ3HSeZb7IrNq8bM2
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# ----------------------------
# Parameters (Gaussian model)
# ----------------------------
mu = 10        # Mean of log-transformed rainfall
sigma = 3      # Standard deviation
n_samples = 10000  # Number of simulated samples

# ----------------------------
# Generate Random Samples
# ----------------------------
samples = np.random.normal(mu, sigma, n_samples)

# Create range for plotting theoretical curves
x = np.linspace(mu - 4*sigma, mu + 4*sigma, 1000)

# ----------------------------
# Plot 1: PDF
# ----------------------------
plt.figure()
plt.hist(samples, bins=50, density=True)
plt.plot(x, norm.pdf(x, mu, sigma))
plt.title("PDF of Log-Transformed Rainfall (Gaussian)")
plt.xlabel("R_dBR")
plt.ylabel("Density")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# ----------------------------
# Parameters (Gaussian model)
# ----------------------------
mu = 10        # Mean of log-transformed rainfall
sigma = 3      # Standard deviation
n_samples = 10000  # Number of simulated samples

# ----------------------------
# Generate Random Samples
# ----------------------------
samples = np.random.normal(mu, sigma, n_samples)

# Create range for plotting theoretical curves
x = np.linspace(mu - 4*sigma, mu + 4*sigma, 1000)
plt.figure()
plt.plot(x, norm.cdf(x, mu, sigma))
plt.title("CDF of Log-Transformed Rainfall (Gaussian)")
plt.xlabel("R_dBR")
plt.ylabel("Cumulative Probability")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm, laplace, lognorm

x = np.linspace(-5,5,1000)

# 1. Gaussian (Noise & Log Rainfall)
plt.figure()
plt.plot(x, norm.pdf(x,0,1))
plt.axvline(0)
plt.title("Gaussian PDF (Stochastic Noise / Log Rainfall)")
plt.show()

# 2. Laplace (Motion Perturbation)
b = 1
plt.figure()
plt.plot(x, laplace.pdf(x,0,b))
plt.axvline(0)
plt.title("Laplace PDF (Motion Perturbation)")
plt.show()

# 3. LogNormal (Rainfall Intensity)
mu = 0
sigma = 1
x_pos = np.linspace(0.01,5,1000)

plt.figure()
plt.plot(x_pos, lognorm.pdf(x_pos, sigma, scale=np.exp(mu)))
plt.axvline(np.exp(mu + sigma**2/2))
plt.title("LogNormal PDF (Rainfall Intensity)")
plt.show()

# 4. Chebyshev Bound Plot
alpha = np.linspace(0.1,5,100)
bound = 1/(alpha**2)

plt.figure()
plt.plot(alpha, bound)
plt.title("Chebyshev Upper Bound (Gaussian)")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Number of samples
n = 10000

# Simulate log-transformed rainfall
Y = np.random.normal(loc=0, scale=1, size=n)

# Compute sample statistics
sample_mean = np.mean(Y)
sample_variance = np.var(Y)

print("Sample Mean:", sample_mean)
print("Sample Variance:", sample_variance)

# Plot histogram
plt.figure()
plt.hist(Y, bins=50, density=True)

# Plot theoretical PDF
x = np.linspace(-4, 4, 1000)
plt.plot(x, norm.pdf(x, 0, 1))

plt.axvline(sample_mean)
plt.title("Simulation of Log-Transformed Rainfall (Gaussian Model)")
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

x = np.linspace(-5, 5, 1000)

plt.figure()
plt.plot(x, norm.pdf(x, 0, 1))
plt.axvline(0)

plt.xlabel("Log-Transformed Rainfall Value (Y)")
plt.ylabel("Probability Density")
plt.title("PDF of Log-Transformed Rainfall (Standard Normal Distribution)")

plt.show()

alpha = np.linspace(0.1, 5, 100)
bound = 1 / (alpha**2)

plt.figure()
plt.plot(alpha, bound)

plt.xlabel("Deviation from Mean (α)")
plt.ylabel("Upper Probability Bound")
plt.title("Chebyshev Inequality Upper Bound")

plt.show()

mu = 0
sigma = 1
x = np.linspace(0.01, 5, 1000)

pdf = lognorm.pdf(x, sigma, scale=np.exp(mu))

EY = 0
exp_EY = np.exp(EY)
E_expY = np.exp(mu + sigma**2/2)

plt.figure()
plt.plot(x, pdf)
plt.axvline(exp_EY)
plt.axvline(E_expY)

plt.xlabel("Rainfall Intensity (R)")
plt.ylabel("Probability Density")
plt.title("Jensen's Inequality for Log-Transformed Rainfall")

plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Define range
x = np.linspace(-5, 5, 1000)

# PDF of standard normal
pdf = norm.pdf(x, 0, 1)

# Expectation
EY = 0

# Plot
plt.figure()
plt.plot(x, pdf, label="PDF of Y ~ N(0,1)")
plt.fill_between(x, pdf, alpha=0.3)

# Plot expectation line
plt.axvline(EY, linestyle='--', label="E[Y] = 0")

plt.xlabel("Log-Transformed Rainfall (Y)")
plt.ylabel("Probability Density")
plt.title("Expectation of Log-Transformed Rainfall")
plt.legend()

plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import norm

# Parameters
mu = 1
sigma = 0.5

# Range of values
x = np.linspace(mu - 4*sigma, mu + 4*sigma, 1000)

# Gaussian PDF
pdf = norm.pdf(x, mu, sigma)

# Plot
plt.figure()
plt.plot(x, pdf, label="PDF of logR ~ N(μ, σ²)")
plt.axvline(mu, linestyle='--', label=f"Mean (μ) = {mu}")

plt.xlabel("Log Rainfall Value (log R)")
plt.ylabel("Probability Density")
plt.title("Gaussian Distribution of Log-Transformed Rainfall")
plt.legend()

plt.show()