# -*- coding: utf-8 -*-
"""Markov.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rqD_7Epmgzi8gE82xPxERNrgjZzx2IAL
"""

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import lognorm

# -----------------------------
# Rainfall Intensity Model
# -----------------------------
# Rainfall is non-negative → Markov applicable

mu_log = 1.0        # mean of log(R)
sigma_log = 1.0     # std of log(R) (heavier tail)
scale = np.exp(mu_log)

# Rainfall threshold range (mm/hr)
k = np.linspace(5, 150, 400)

# True exceedance probability from lognormal model
true_prob = 1 - lognorm.cdf(k, s=sigma_log, scale=scale)

# Mean rainfall (needed for Markov bound)
mean_R = lognorm.mean(s=sigma_log, scale=scale)

# Markov inequality bound
markov_bound = mean_R / k

# -----------------------------
# Plot
# -----------------------------
plt.figure(figsize=(8,6))

plt.plot(k, true_prob, label="True Probability  P(R ≥ k)", linewidth=2)
plt.plot(k, markov_bound, '--', label="Markov Bound  E[R]/k", linewidth=2)

plt.yscale("log")   # IMPORTANT for heavy-tail visualization
plt.xlabel("Rainfall Threshold k (mm/hr)")
plt.ylabel("Probability (log scale)")
plt.title("Rainfall Intensity: Lognormal vs Markov’s Inequality")
plt.legend()
plt.grid(True)

plt.show()

print("Mean Rainfall E[R] =", round(mean_R, 3))



import numpy as np
import matplotlib.pyplot as plt

# Mean of random variable R
E_R = 10   # You can change this value

# Threshold values k
k = np.linspace(1, 50, 500)

# Markov Bound: P(R >= k) ≤ E[R] / k
markov_bound = E_R / k

# Plot
plt.figure()
plt.plot(k, markov_bound)

plt.xlabel("Threshold k")
plt.ylabel("E[R] / k")
plt.title("Markov Bound vs Threshold (1/k Decay)")
plt.ylim(0, E_R)

plt.show()

import numpy as np
import matplotlib.pyplot as plt

# Parameters
size = 10000

# Generate distributions
normal_data = np.random.normal(loc=10, scale=2, size=size)
lognormal_data = np.random.lognormal(mean=2, sigma=0.8, size=size)

# Plot PDFs
plt.figure(figsize=(10,5))
plt.hist(normal_data, bins=100, density=True, alpha=0.6, label='Gaussian')
plt.hist(lognormal_data, bins=100, density=True, alpha=0.6, label='Lognormal')
plt.xlim(0, 50)
plt.xlabel('Value')
plt.ylabel('Probability Density')
plt.title('Gaussian vs Lognormal Distribution')
plt.legend()
plt.show()

import numpy as np
import matplotlib.pyplot as plt
from scipy.stats import lognorm

# ---- Parameters in dBR domain ----
mu_dB = 0      # mean in dBR (small mean → peak near low rainfall)
sigma_dB = 5   # standard deviation in dBR

# ---- Convert to natural log domain ----
mu_ln = (mu_dB * np.log(10)) / 10
sigma_ln = (sigma_dB * np.log(10)) / 10

# ---- Rainfall intensity range ----
R = np.linspace(0.01, 50, 1000)

# ---- Lognormal PDF and CDF ----
pdf_R = lognorm.pdf(R, s=sigma_ln, scale=np.exp(mu_ln))
cdf_R = lognorm.cdf(R, s=sigma_ln, scale=np.exp(mu_ln))

# ---- Plot ----
plt.figure(figsize=(10,4))

plt.subplot(1,2,1)
plt.plot(R, pdf_R, linewidth=2)
plt.title("PDF of Rainfall Intensity (Log-normal)")
plt.xlabel("Rainfall Intensity (mm/hr)")
plt.ylabel("PDF")
plt.grid(True)

plt.subplot(1,2,2)
plt.plot(R, cdf_R, linewidth=2)
plt.title("CDF of Rainfall Intensity (Log-normal)")
plt.xlabel("Rainfall Intensity (mm/hr)")
plt.ylabel("CDF")
plt.grid(True)

plt.tight_layout()
plt.show()